# Generated by Django 4.2 on 2025-08-11 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Company')),
                ('slogan', models.CharField(default='', max_length=100, verbose_name='Company Slogan')),
                ('description', models.CharField(default='', max_length=500, verbose_name='Company Description')),
                ('phone', models.IntegerField(verbose_name='Company Phone Number')),
                ('website', models.CharField(default='', max_length=100, verbose_name='Company Website')),
                ('employee_number', models.IntegerField(verbose_name='No Of Employees')),
                ('started', models.DateField(verbose_name='Started Rate')),
                ('photo', models.ImageField(upload_to='company/', verbose_name='Company Image in jpg/png Format')),
                ('license', models.FileField(upload_to='license/', verbose_name='Company Licence in pdf Format')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies/',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to='resumes/')),
                ('extracted_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=75, verbose_name='Job Title')),
                ('type', models.CharField(default='', max_length=60, verbose_name='Job Type')),
                ('location', models.CharField(default='', max_length=50, verbose_name='Job Location')),
                ('des', models.CharField(default='', max_length=500, verbose_name='Job Description')),
                ('reqirement', models.CharField(default='', max_length=300, verbose_name='Job Requirements')),
                ('reference', models.CharField(blank=True, default='POST-917101', max_length=15, unique=True)),
                ('start_date', models.DateField(auto_now=True)),
                ('application_deadline', models.DateField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'DRAFT'), (1, 'OPEN'), (2, 'EXPIRED'), (3, 'ARCHIVED')], default=1, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('salary', models.TextField(default='NOT DISCLOSED', verbose_name='Salary Package')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('other_information', models.TextField(blank=True, default=None, help_text='Additional details (special conditions, benefits, recruitment process, etc.)', null=True, verbose_name='Other informations')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.company')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
