# Generated by Django 4.2 on 2025-08-21 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='des',
            new_name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Not Selected', max_length=25),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_number',
            field=models.IntegerField(default=1, verbose_name='No Of Employees'),
        ),
        migrations.AlterField(
            model_name='company',
            name='started',
            field=models.DateField(default=datetime.date.today, verbose_name='Started Rate'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference',
            field=models.CharField(blank=True, default='POST-830837', max_length=15, unique=True),
        ),
    ]
