# Generated by Django 4.2 on 2025-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_des_post_description_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reference',
            field=models.CharField(blank=True, default='POST-863376', max_length=15, unique=True),
        ),
    ]
