# Generated by Django 4.2 on 2025-08-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_post_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reference',
            field=models.CharField(blank=True, default='POST-550483', max_length=15, unique=True),
        ),
    ]
