# Generated by Django 4.2 on 2025-08-21 16:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_post_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='other_information',
            field=ckeditor.fields.RichTextField(blank=True, default='<p>Lorem ipsum sit ...</p>', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='reference',
            field=models.CharField(blank=True, default='POST-210825', max_length=15, unique=True),
        ),
    ]
