# Generated by Django 4.2 on 2025-08-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_post_other_information_alter_post_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='reqirement',
            new_name='requirement',
        ),
        migrations.AlterField(
            model_name='post',
            name='reference',
            field=models.CharField(blank=True, default='POST-784205', max_length=15, unique=True),
        ),
    ]
