# Generated by Django 4.2 on 2025-08-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_reqirement_post_requirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reference',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
