# Generated by Django 4.2 on 2025-07-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'USER'), (2, 'STUDENT'), (3, 'ENTERPRISE'), (4, 'PROFESSOR'), (5, 'ADMIN')], null=True),
        ),
    ]
