# Generated by Django 4.2 on 2025-08-08 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='', max_length=250, verbose_name='Your Address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Of Birth'),
        ),
    ]
